### ISSUE TITLE
Can't use custom data objects

### ISSUE THREAD

**Issue by connor-sleight** [triniwiz/nativescript-accordion#15]
The accordion doesn't accept a custom data object, it provides the following error. Why is it looking for a property `Symbol`?
```JS: EXCEPTION: Uncaught (in promise): Error: Error in /data/data/org.nativescript.SMBarcode/files/app/scanTypeViews/worksOrder/worksOrder.html:
26:27 caused by: Cannot read property 'Symbol' of undefined
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: Error in /data/data/org.nativescript.SMBarcode/files/app/scanTypeViews/worksOrder/worksOrder.html:26:2
7 caused by: Cannot read property 'Symbol' of undefined
JS:     at resolvePromise (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescri
pt.js:416:31)
JS:     at resolvePromise (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescri
pt.js:401:17)
JS:     at file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:17
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-n
ativescript.js:223:37)
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/@angular/core/bundles/core.umd.js:5966:41)
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-n
ativescript.js:222:42)
JS:     at Zone.runTask (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript
.js:123:47)
JS:     at drainMicroTaskQueue (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativ
escript.js:355:35)
JS: Unhandled Promise rejection: Error in /data/data/org.nativescript.SMBarcode/files/app/scanTypeViews/worksOrder/worksOrder.html:26:27 caused
 by: Cannot read property 'Symbol' of undefined ; Zone: angular ; Task: Promise.then ; Value: Error: Error in /data/data/org.nativescript.SMBar
code/files/app/scanTypeViews/worksOrder/worksOrder.html:26:27 caused by: Cannot read property 'Symbol' of undefined TypeError: Cannot read prop
erty 'Symbol' of undefined
JS:     at Object.getSymbolIterator (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/lang-facade.js:36:
34)
JS:     at Object.isListLikeIterable (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-angular/collection-facade
.js:9:27)
JS:     at AccordionComponent.set [as items] (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/nativescript-accordion/angular
/index.js:127:68)
JS:     at Wrapper_AccordionComponent.check_items (/AccordionModule/AccordionComponent/wrapper.ngfactory.js:19:24)
JS:     at CompiledTemplate.proxyViewClass.View_WorksOrderComponent0.detectChangesInternal (/AppModule/WorksOrderComponent/component.ngfactory.
js:97:32)
JS:     at CompiledTemplate.proxyViewClass.AppView.detectChanges (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/@angular/c
ore/bundles/core.umd.js:9354:18)
JS:     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/@angu
lar/core/bundles/core.umd.js:9447:48)
JS:     at CompiledTemplate.proxyViewClass.View_WorksOrderComponent_Host0.detectChangesInternal (/AppModule/WorksOrderComponent/host.ngfactory.
js:29:19)
JS:     at CompiledTemplate.proxyViewClass.AppView.detectChanges (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/@angular/c
ore/bundles/core.umd.js:9354:18)
JS:     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (file:///data/data/org.nativescript.SMBarcode/files/app/tns_modules/@angu
lar/core/bundles/core.umd.js:9447:48)
JS: Error: Uncaught (in promise): Error: Error in /data/data/org.nativescript.SMBarcode/files/app/scanTypeViews/worksOrder/worksOrder.html:26:2
7 caused by: Cannot read property 'Symbol' of undefined

**Comment by triniwiz** [comment]
what does your data look like ?

**Comment by mast3rd3mon** [comment]
I can't show you the data itself but here is an interface which is the same as the JSON data
```
export interface TtWorksOrder {
    iWoNo: number,
    iSoNo: number,  
    cOtherRef: string,
    iRevNo: number,
    cOrdType: string,
    cCustomerAddress: string,
    cDeliveryAddress: string,
    cCustomerOrderRef: string,  
    cCompanyName: string, 
    cCustomerName: string,
    cLoggedBy: string,
    cDeliveryInstruct: string,
    cCustno: string,
    iSalCon: number,
    cCustomerQuadrant: string,
    ttItem?: TtItem[]
}

**Comment by NZasepa** [comment]
If you're getting these data from an API, try to use "async" pipe, e.g. [items]="sideDrawerItems | async"

**Comment by mast3rd3mon** [comment]
@NZasepa why? i dont need to?
