### ISSUE TITLE
Not working in angular version

### ISSUE THREAD

**Issue by Habeeb-mohamed** [triniwiz/nativescript-accordion#3]
In iOS, When i try to implement i have following error
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x7302a9 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0xbe4155 ffi_closure_inner_SYSV
3   0xbe80b8 ffi_closure_SYSV
4   0x1ff41841 <redacted>
5   0x1ff3578f <redacted>
6   0x221423af <redacted>
7   0xbe802c ffi_call_SYSV
8   0xbe3e99 ffi_call
9   0x6fc397 NativeScript::FFICall::call(JSC::ExecState*)
10  0x9c7daf JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
11  0x9c782b llint_slow_path_call
12  0x9cef4b llint_entry
13  0x9cef0d llint_entry
14  0x9c9801 vmEntryToJavaScr
ipt
15  0x97fedf JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*)
16  0x96281f JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
17  0xa8db77 JSC::call(JSC::ExecSt
ate*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
18  0x72ff9f NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::callFunction(JSC::JSValue const&, JSC::ArgList const&, void*)
19  0x72fc07 NativeScript:
:ObjCMethodCallback::ffiClosureCallback(void*, void**, void*)
20  0x73028d NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
21  0xbe4155 ffi_closure_inner_SYSV
22  0xbe80b8 ffi_closure_SYSV
23  0x22148299 <redacted>
24  0x222ced2d <redacted>
25  0x221e74ef <redacted>
26  0x221e7197 <redacted>
27  0x221e7115 <redacted>
28  0x2212dd6d <redacted>
29  0x1ff41841 <redacted>
30  0x1ff3578f <redacted>
31  0x1ff3561f <redacted>
JavaScript stack trace:
1   onLayout@file:///app/tns_modules/nativ
escript-accordion/accordion.js:93:19
2   layout@file:///app/tns_modules/ui/core/view.js:104:26
3   layoutChild@file:///app/tns_modules/ui/core/view-common.js:962:21
4   @file:///app/tns_modules/ui/layouts/stack-layout/stack-layout.js:112:36
5   eachLay
outChild@file:///app/tns_modules/ui/layouts/layout-base-common.js:162:21
6   layoutVertical@file:///app/tns_modules/ui/layouts/stack-layout/stack-layout.js:109:29
7   onLayout@file:///app/tns_modules/ui/layouts/stack-layout/stack-layout.js:78:32
8   lay
out@file:///app/tns_modules/ui/core/view.js:104:26
9   layoutChild@file:///app/tns_modules/ui/core/view-common.js:962:21
10  onLayout@file:///app/tns_modules/ui/page/page.js:394:32
11  layout@file:///app/tns_modules/ui/core/view.js:104:26
12  layoutCh
```

In Android

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'length' of undefined
File: "/data/data/org.nativescript.LazyFetch/files/app/tns_modules/nativescript-accordion/accordion.js, line: 75, column: 22

StackTrace: 
	Frame: function:'AccordionListAdapter.getGroupCount', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/nativescript-accordion/accordion.js', line: 146, column: 32
	Frame: function:'Accordion._createUI', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/nativescript-accordion/accordion.js', line: 75, column: 23
	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 202, column: 14
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 153, column: 14
	Frame: function:'eachChild', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.LazyFetch/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

Thanks in advance

**Comment by triniwiz** [comment]
try updating to `2.1.0`

**Comment by GlisboaDev** [comment]
I'm also having trouble to use the angular version.

I was testing the example code for angular and apparently if more than one element is added the app crashes.

Here is what I got:

```
1   0x1087337cb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x108e081ee ffi_closure_unix64_inner
3   0x108e08b22 ffi_closure_unix64
4   0x10f78dbf8 -[CALayer layoutSublayers]
5   0x10f781440 CA::Layer::layout_if_needed(CA::Transaction*)
6   0x109a49928 -[UIView(Hierarchy) layoutBelowIfNeeded]
7   0x108e0897d ffi_call_unix64
8   0x1297efbd0
file:///app/tns_modules/tns-core-modules/ui/content-view/content-view.js:37:91: JS ERROR Error: More than one layout child inside a ContentView
```

**Comment by GlisboaDev** [comment]
I was playing with the example and trying to put it to work, I just noticed it's missing a parameter in the angular initialization: `headerColor` if you don't add this the app crashes on attempt to load.

**Comment by triniwiz** [comment]
Update to 3.0
