### ISSUE TITLE
Getting error Calling js method onCreateView failed

### ISSUE THREAD

**Issue by gopalshimpi** [triniwiz/nativescript-accordion#56]
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err:
System.err: TypeError: Cannot read property 'length' of undefined
System.err: File: "file:///data/data/org.nativescript.ofypets/files/app/tns_modules/nativescript-accordion/accordion.js, line: 170, column: 33
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'AccordionListAdapter.getChildrenCount', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/nativescript-accordion/accordion.js', line: 632, column: 77
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/nativescript-accordion/accordion.js', line: 170, column: 34
System.err: 	Frame: function:'Accordion.initNativeView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/nativescript-accordion/accordion.js', line: 169, column: 34
System.err: 	Frame: function:'ViewBase.setNativeView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 547, column: 18
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 526, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 642, column: 19
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.ofypets/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:171)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6635)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Executing before-shouldPrepare hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/before-shouldPrepare/nativescript-dev-webpack.js
Executing before-prepare hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/before-prepare/nativescript-dev-sass.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/before-prepare/nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Preparing project...
Executing before-prepareJSApp hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/before-prepareJSApp/nativescript-dev-webpack.js
Project successfully prepared (Android)
Executing after-prepare hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/after-prepare/nativescript-dev-sass.js
Executing after-prepare hook from /Users/gopal/Projects/nativeapps/Ofypets/hooks/after-prepare/nativescript-dev-webpack.js
Successfully transferred payment-modes.component.html on device 51f6c407.
Refreshing application on device 51f6c407...
Successfully synced application org.nativescript.ofypets on device 51f6c407.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Warning: Setting the 'itemHeight' property of 'ListViewGridLayout' is not supported by the Android platform.
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
12-28 11:49:07.411  7095  7095 I zygote  :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.
```

**Comment by bjai** [comment]
i am also getting the same issue @gopalshimpi did you find any work around

**Comment by arnasdev** [comment]
@bjai @gopalshimpi
Fixed this by adding childItems = "blah" to the accordion and using the default data provided

`  <Accordion height="100%" childItems="blah" [items]="items" allowMultiple="false" [selectedIndexes]="selectedIndexes">`

**Comment by arnasdev** [comment]
Still having issues hooking this up to my own data though, more documentation would be appreciated as any change I make seems to be breaking.

**Comment by jeyhunr** [comment]
I have the same problem as well. Thanks to @arnasdev , I have 'temporarily' solved it using childItems="blah". But to be honest, I don't think that's a good solution
